# Generated by Django 3.2.6 on 2021-08-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('not_done', 'Not done')], max_length=20),
        ),
    ]
